### PR TITLE
Earl would like to join this project

### PR DESCRIPTION
**Pull request by ChristopherBignamini**
Even if he hates you...

### CODE REVIEW

**Review by paoloerre — CHANGES_REQUESTED** [review]
The breed isn't my favourite
(...he does look like Aly though)

**Comment by paoloerre** [comment]
Come on @ChristopherBignamini fix the change in your branch!
Can't accept it otherwise.
And you want me to merge it to the master don't you? <3

**Comment by ChristopherBignamini** [comment]
I want you to merge my branch as it is.

**Comment by ChristopherBignamini** [comment]
Alyearl

**Comment by paoloerre** [comment]
ok for fuck sake let's merge this shit!

**Pull request merged**
